name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
        name: Cargo build
  crates:
    runs-on: ubuntu-latest
    needs: compile
    if: ${{ github.event.head_commit.message == ':rocket:' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish
        run: cargo publish

