name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Cargo:
    runs-on: ubuntu-latest
    image:
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag joaopedropp/interstella5555
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: joaopedropp
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push joaopedropp/interstella5555


